libavformat/movenc.c: Fix mov_write_mhac_tag
There is a new code function added on vanilla FFmpeg repository, but very different comparison: https://github.com/FFmpeg/FFmpeg/commit/c683fc8375156ded2f76defddae080a7f6614762
https://github.com/FFmpeg/FFmpeg/commit/a7b0af0071c0d95f657719372a84bea7c6fd84f3

So the old code function of mov_write_mhac_tag in between line 1350 and 1359 were removed.

Before fix, error outputs:

```
libavformat/movenc.c:1350:12: error: conflicting types for 'mov_write_mhac_tag'; have 'int(AVIOContext *, MOVTrack *)'
 1350 | static int mov_write_mhac_tag(AVIOContext *pb, MOVTrack *track)
      |            ^~~~~~~~~~~~~~~~~~
libavformat/movenc.c:973:12: note: previous definition of 'mov_write_mhac_tag' with type 'int(AVFormatContext *, AVIOContext *, MOVTrack *)'
  973 | static int mov_write_mhac_tag(AVFormatContext *s, AVIOContext *pb, MOVTrack *track)
      |            ^~~~~~~~~~~~~~~~~~
libavformat/movenc.c: In function 'mov_write_audio_tag':
libavformat/movenc.c:1603:34: error: passing argument 1 of 'mov_write_mhac_tag' from incompatible pointer type [-Wincompatible-pointer-types]
 1603 |         ret = mov_write_mhac_tag(s, pb, track);
      |                                  ^
      |                                  |
      |                                  AVFormatContext *
libavformat/movenc.c:1350:44: note: expected 'AVIOContext *' but argument is of type 'AVFormatContext *'
 1350 | static int mov_write_mhac_tag(AVIOContext *pb, MOVTrack *track)
      |                               ~~~~~~~~~~~~~^~
libavformat/movenc.c:1603:37: error: passing argument 2 of 'mov_write_mhac_tag' from incompatible pointer type [-Wincompatible-pointer-types]
 1603 |         ret = mov_write_mhac_tag(s, pb, track);
      |                                     ^~
      |                                     |
      |                                     AVIOContext *
libavformat/movenc.c:1350:58: note: expected 'MOVTrack *' but argument is of type 'AVIOContext *'
 1350 | static int mov_write_mhac_tag(AVIOContext *pb, MOVTrack *track)
      |                                                ~~~~~~~~~~^~~~~
libavformat/movenc.c:1603:15: error: too many arguments to function 'mov_write_mhac_tag'; expected 2, have 3
 1603 |         ret = mov_write_mhac_tag(s, pb, track);
      |               ^~~~~~~~~~~~~~~~~~        ~~~~~
libavformat/movenc.c:1350:12: note: declared here
 1350 | static int mov_write_mhac_tag(AVIOContext *pb, MOVTrack *track)
      |            ^~~~~~~~~~~~~~~~~~
```

- 2026 Martin Eesmaa