libavformat/movenc.c: Remove old code MPEGH-3D-AUD
The lines were removed because it's already there in between line 1592 and 1593, looks like it's already implemented on official FFmpeg repository.

Errors short log before fixing the bug:

```
libavformat/movenc.c:1632:28: error: passing argument 1 of 'mov_write_mhac_tag' from incompatible pointer type [-Wincompatible-pointer-types]
libavformat/movenc.c:1632:31: error: passing argument 2 of 'mov_write_mhac_tag' from incompatible pointer type [-Wincompatible-pointer-types]
```

- 2026 Martin Eesmaa